# Generated by Django 4.1.6 on 2023-04-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='article',
            new_name='articles',
        ),
    ]
